### PR TITLE
URGENT: BUG-FIX (and heavy optimization of prime-related functions)

### PR DESCRIPTION
**Pull request by kckennylau**

### CODE REVIEW

**Comment by kckennylau** [comment]
DO NOT MERGE YET
there is still bugs

**Comment by kckennylau** [comment]
In the future could you please write more tests?

**Comment by kckennylau** [comment]
Passed my tests.

**Comment by Mego** [comment]
Why on earth did you write a custom `isqrt` function? Surely `int(n**.5+1)` would be much faster.

**Comment by kckennylau** [comment]
I was worried about floating point inaccuracies... also, I believe `sqrt(n)` would be faster than `n**.5`.

**Comment by kckennylau** [comment]
And I do not think that this is a matter more urgent than the bugfix?

**Comment by Mego** [comment]
I'll merge it, but I'm changing it back to `math.sqrt`. The native C code for the `math` library will certainly be faster than the Python code.

**Pull request merged**
