### PR TITLE
Update tests.py

### PR DESCRIPTION
**Pull request by kckennylau**

### CODE REVIEW

**Comment by Mego** [comment]
The second parameter is a list representing the stack - you want `[[4,4,4,4,4]]` as the test result, not `[4,4,4,4,4]`.

**Comment by Mego** [comment]
It doesn't seem to be working. Does your branch include the change from #62?

**Comment by kckennylau** [comment]
What do you mean?

**Comment by Mego** [comment]
You added a unit test for the command you added in #62, but your branch (patch-8) doesn't include the added command, so the test is failing.

**Pull request closed without merging**
